name: Go CI
run-name: ${{ github.actor }} is making a push to main ğŸš€
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v4
        run: echo "Checking out repository to runner ğŸƒ"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        run: echo "Setting up Go âœ¨"

      - name: Build
        run: echo "Building...ğŸ”¨"
        run: go build ./main.go

      - name: Test
        run: echo "Running test... ğŸ§‘â€ğŸ”¬"
        run: go test ./test
